"""Initial migration

Revision ID: 146d23fe2a24
Revises: 720cfa45f794
Create Date: 2024-06-26 02:21:47.308462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146d23fe2a24'
down_revision = '720cfa45f794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_first_login', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_first_login')
    # ### end Alembic commands ###
